version = 0.1
[default.deploy.parameters]
stack_name = "expense-tracker"
resolve_s3 = true
s3_prefix = "expense-tracker"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
